name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: MaterialInOut
      run: docker build . --file Dockerfile --tag sebug/material-in-out:$(git rev-parse --short HEAD)
